version: '3.3'

services:
  server:
    build:
      context: ./infrastructure/server/nginx
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:80
      - ${SSL_PORT}:443
    volumes:
      - type: bind
        source: ${APP_PATH}
        target: ${DOCUMENT_ROOT}
      - type: bind
        source: ./infrastructure/server/nginx/sites/site.conf
        target: /etc/nginx/conf.d/site.conf
      - type: bind
        source: ./infrastructure/logs/nginx-error.log
        target: /var/log/nginx/error.log
      - type: bind
        source: ./infrastructure/logs/nginx-access.log
        target: /var/log/nginx/access.log
    container_name: LEMP_nginx
    depends_on:
      - php
      - database
    networks:
      - LEMP

  php:
    build:
      context: ./infrastructure/php
      dockerfile: Dockerfile
    ports:
      - ${PHP_PORT}:9000
    volumes:
      - type: bind
        source: ${APP_PATH}
        target: ${DOCUMENT_ROOT}
      - type: bind
        source: ./infrastructure/php/www.conf
        target: /usr/local/etc/php-fpm.d/www.conf
    container_name: LEMP_php
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - LEMP

  database:
    build:
      context: ./infrastructure/database/mysql
      dockerfile: Dockerfile
    container_name: LEMP_mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - LEMP

networks:
  LEMP:
    driver: bridge
