version: '3.3'

services:
  server:
    build:
      context: ./infrastructure/server/nginx
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${DOCUMENT_ROOT_PORT}
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
      - ./infrastructure/server/nginx/sites-enabled/mylara.conf:/etc/nginx/conf.d/default.conf
      - ./infrastructure/server/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./infrastructure/server/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./infrastructure/logs/nginx-error.log:/var/log/nginx/error.log
      - ./infrastructure/logs/nginx-access.log:/var/log/nginx/access.log
    container_name: LEMP_nginx
    restart: always
    links:
      - php
    networks:
      - LEMP

  php:
    build:
      context: ./infrastructure/php
      dockerfile: Dockerfile
    ports:
      - ${PHP_PORT}:9000
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
      - ./infrastructure/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    container_name: LEMP_php
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    links:
      - database
    networks:
      - LEMP

  database:
    build:
      context: ./infrastructure/database/mysql
      dockerfile: Dockerfile
    container_name: LEMP_mysql
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - LEMP

networks:
  LEMP:
    driver: bridge
